name: 08 - Using Variables

on: 
    push:
    workflow_dispatch:
env:
    WORKFLOW_VAR: "I am a work flow var"
    OVERWRITTEN: "I will be overwritten"
jobs:
    echo:
        runs-on: ubuntu-latest
        env:
           JOB_VAR: "I am a job var"  
           OVERWRITTEN: " have been overwritten at JOb Level"
        steps:
            - name: Print Env Variables
              env:
                STEP_VAR: "i am a step env var" 
                step_var2: "I am another step env var"
            run: |
                echo "Step env var : ${{env.STEP_VAR}}"
                echo "Step env var 2 : $step_var2"
                echo "Jon env var: ${{env.JOB_VAR}}"
                echo "Jon env var: ${{env.WORKFLOW_VAR}}"
                echo "Jon env var: ${{env.OVERWRITTEN}}"
          - name: "Override Job variables"
            env:
               OVERWRITTEN: "I have been overwritten at Step Level"
            run: |
               echo "Jon env var: ${{env.OVERWRITTEN}}"