name: 13 - Using Caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
              description: Whether to execute cache step
              type: boolean
              default: true
jobs:
    build: 
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: 13-caching/react-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install Dependencies
              run: npm cli
            - name: Testing
              run: npm run test
              
            - name: Building
              run: np run build
            - name: Deploy to non-prod
              run: echo " Deploying to non prod"
    #1. Checkout the code
    #2. Instal dependencies
    #3. unitesting and building
    #4. Deploy to NOn-Prod env
